### PR TITLE
fix for the implementation in ion-inputs.

### PR DESCRIPTION
**Pull request by lhpaul**
Now the directive is loaded after ngAfterViewInit event instead of ngOnInit

### CODE REVIEW

**Comment by lhpaul** [comment]
I cant find where the problem with SyncTestZoneSpec is originated

**Comment by BioPhoton** [comment]
Hy, sry!! I'm in the process of changing the testing a bit. I will fix this!!!

And BIIIIIGGGG THX for the PR.

**Comment by lhpaul** [comment]
#1 Thanks to you!

**Comment by BioPhoton** [comment]
Hi again. I'm finished with the test stuff...

Could you do me a favour:
- pull my latest changes
- npm run build
- copy dist into ./examples/angular4/node_modules/angular-formatter-parser
- cd into ./examples/angular4
- run ng serve
- test if you can use the inputs

Best Michael

**Comment by lhpaul** [comment]
Done.

Please check my code because there might be a better solution.

Thxs

**Review by BioPhoton — COMMENTED** [review]
Looks good! THX!!

I just have one question: 
If ionic is given you would set inputElement tiwice. once in the ngOnInit, and another time in ngOnAfterViewInit.

Is there a reason for?

Best 
Michael

**Comment by BioPhoton** [comment]
Hi @lhpaul ,
could you please give it a quick try in ionic? If it works i will release it.

Would save me time.

best michael

**Comment by cmolina** [comment]
Hi! When could we try this feature in a new version? :)
We really need this 🔝

**Comment by BioPhoton** [comment]
Hi @camolin3 i reopened the issue because i got bad outcome in a real inplementation. See #1. I guess it will take some time.

**Pull request merged**
